import './global.css';
import '/node_modules/sal.js/dist/sal.css';
import './src/js/form.js';
import './src/js/fileDownload.js';
import './src/js/copyToClipboard.js';
import './src/styles/toastify.css';
import './src/styles/header.css';
import './src/styles/content.css';
import './src/styles/footer.css';
import sal from 'sal.js';
sal();
